version: '3.8'

services:
  app:
    container_name: app
    image: personal-site-dev:latest
    env_file: .env
    environment: 
      - ENVIRONMENT=development
    volumes:
      - "./app:/app"
    ports:
      - "5000:5000"
