version: '3.8'

services:
  app:
    container_name: app
    image: personal-site-prod:latest
    command: gunicorn --bind 0.0.0.0:5000 --access-logfile - --error-logfile - "app:create_app('production')"
    env_file: .env
    environment:
      - ENVIRONMENT=production
  nginx:
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - app