version: '3.8'

services:
  app:
    container_name: app
    image: personal-site-dev:latest
    command: gunicorn --bind 0.0.0.0:5000 --access-logfile - --error-logfile - --reload "app:create_app('development')"
    env_file: .env
    volumes:
      - "./app:/app"
    ports:
      - "5000:5000"
